version: '3.4'

services:
  db:
    container_name: databasepxti
    image: pxtidb
    build:
      context: .
      dockerfile: ./database/Dockerfile
    ports:
      - 1433:1433
    volumes:
      - type: bind
        source: ./database/mssqldata
        target: /var/opt/mssql

volumes:
  mssqldata:
